### PR TITLE
Typo in Readme.md

### PR DESCRIPTION
**Pull request by arnavjindal**
--

### CODE REVIEW

**Comment by SomnathDas** [comment]
bruh!

**Comment by arnavjindal** [comment]
> bruh!

Stonks!

**Comment by arnavjindal** [comment]
Hey @SomnathDas, why commit urself when u can merge bruh...? (+Me curious 🦝.)

**Comment by SomnathDas** [comment]
:eyes: There was a conflict in merging... 
so i said 'Fine i will do it myself'

**Comment by arnavjindal** [comment]
It doesn't seems to be changed yet...🗼

**Comment by SomnathDas** [comment]
> It doesn't seems to be changed yet...tokyo_tower

Done!

**Pull request merged**
